require "rake"
require "rspec/core/rake_task"
require "rubocop/rake_task"

# Define RSpec task
RSpec::Core::RakeTask.new(:spec)

# Define RuboCop task
RuboCop::RakeTask.new(:rubocop) do |task|
  task.patterns = ["**/*.rb"]
end

# Define default task to run both RSpec and RuboCop
task default: [:spec, :rubocop]
